#!/bin/bash
# auto cat every sec
echo "auto_cat 0 <=<=<=<=<=<=<=<=<=<="

if [ "$1" = "" ]; then
	echo "no input file or cmd (-c <CMD>)"
else
	if [ "$1" =  "-c" ]; then
		if [ "$2" = "" ]; then
			echo "no input cmd (-c <CMD>)"
		else
			i=1
			until [ ] 
			do
				$2
				sleep 1
				echo "auto_cat $i <=<=<=<=<=<=<=<=<=<="
				i=$[i+1]
			done
		fi
	else
		i=1
		until [ ] 
		do
			cat $1
			sleep 1
			echo "auto_cat $i <=<=<=<=<=<=<=<=<=<="
			i=$[i+1]
		done
	fi
fi


