#!/usr/bin/python
import os
from subprocess import check_output

selected_files = os.environ["NAUTILUS_SCRIPT_SELECTED_FILE_PATHS"].strip().split("\n")
selected_files = [os.path.basename(x) for x in selected_files]

output_file = check_output(["zenity", "--file-selection", "--save", "--confirm-overwrite"]).strip()

selected_file_list_str = ""
for x in selected_files:
    selected_file_list_str += " '" + x +"' "

os.system("pdftk " + selected_file_list_str + " cat output" + " '" + output_file + "'")

