[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "dotfile"
version = "1"

[tool.setuptools.packages.find]
where = ["dotfiles"]
namespaces = true

[project.scripts]
dotfiles = "dotfiles:main"

