#!/bin/bash

#requirements
#create firefox profile "sshproxy"
#>firefox -p
#set SOCKS Proxy
#>about:config
#>network.proxy.type=1
#>network.proxy.socks=localhost
#>network.proxy.socks_port=8080
#>network.proxy.socks_remote_dns=true


#source https://calomel.org/firefox_ssh_proxy.html

if [ "$#" = 1 ]; then
    firefox -p "sshproxy" &

    #-C compression
    #-T no pseudo-terminal
    #-n ssh in background, redirects stdin to /dev/null
    #-N do not execute remote command
    #-D dynamic port bindingg
    ssh -CqTnN -D 8080 $1
    wait
else
    echo "firefox_tunnel_to <remote_host>"
fi

