#!/usr/bin/python3

import sys
import subprocess
import datetime

def run():
    cmd = " ".join(sys.argv[1:])
    start = datetime.datetime.now()
    output = subprocess.getoutput(cmd)
    stop = datetime.datetime.now()
    if output != "":
        print(output)
    duration = stop - start
    print(str(duration.seconds) + "sec ", end="")
    print(str(int(duration.microseconds/1000)) + "ms")

if __name__ == "__main__":
    run()
